services:
  db:
    image: postgres:latest
    container_name: expense-db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/expense_db?sslmode=disable
      JWT_SECRET: supersecretkey
    restart: always

volumes:
  pgdata:
